#
# Module manifest for module 'PSNVIDIA.DLS'
#
# Generated by: erikgraa
#
# Generated on: 25.05.2025
#

@{
    RootModule = 'PSNVIDIA.DLS.psm1'

    ModuleVersion = '0.2505.2'

    CompatiblePSEditions = @('Core')

    GUID = '619e94f1-d0be-43d6-a4ba-dc78a8211e13'

    Author = 'erikgraa'

    Copyright = 'Copyright (c) 2025 erikgraa, licensed under the MIT License.'

    Description = 'A PowerShell module for various NVIDIA Delegated License System actions.'

    PowerShellVersion = '7.4'

    FunctionsToExport = @('Connect-NVDLS', 'Disconnect-NVDLS', 'Get-NVDLSInstance', 'Get-NVDLSLease'
                        'Get-NVDLSUser', 'Get-NVDLSLicenseServer', 'New-NVDLSClientConfigurationToken')

    PrivateData = @{
        PSData = @{
            Tags = @(
                'NVIDIA', 'PowerShell', 'PowerShell-Core'
            )

            ProjectUri     = 'https://github.com/erikgraa/PSNVIDIA.DLS'
            License        = 'https://github.com/erikgraa/PSNVIDIA.DLS/blob/main/LICENSE'
            ReleaseNotes   = 'https://github.com/erikgraa/PSNVIDIA.DLS'
        }
    }
}